/**
 * skylark-utils - An Elegant HTML5 JavaScript Library.
 * @author Hudaokeji Co.,Ltd
 * @version v0.9.0
 * @link www.skylarkjs.org
 * @license MIT
 */
define(["./skylark","./langx","./finder"],function(t,e,r){function n(t,e,r){null==r?t.removeAttribute(e):t.setAttribute(e,r)}function i(t,e,r){if(void 0!==r)return t.setAttribute(e,r),this;if("object"==typeof e){for(var n in e)i(t,n,e[n]);return this}return t.hasAttribute(e)?t.getAttribute(e):void 0}function a(t){var r={};return e.each(t.attributes||[],function(t,e){0==e.name.indexOf("data-")&&(r[g(e.name.replace("data-",""))]=y(e.value))}),r}function o(t,e){var r=t._$_store;return!r&&e&&(r=t._$_store=a(t)),r}function u(t,e){if(void 0===e)return o(t,!0);var r=o(t);if(r){if(e in r)return r[e];var n=g(e);if(n in r)return r[n]}var a="data-"+e.replace(A,"-$1").toLowerCase();return i(t,a)}function l(t,e,r){var n=o(t,!0);n[g(e)]=r}function c(t,e,r){if(void 0===r){if("object"==typeof e){for(var n in e)l(t,n,e[n]);return this}return u(t,e)}return l(t,e,r),this}function f(t,r){e.isString(r)&&(r=r.split(/\s+/));var n=o(t,!0);return r.forEach(function(t){delete n[t]}),this}function s(t,e){return b.call(t,function(t){return t[e]})}function d(t,e,r){return e=C[e]||e,void 0===r?t[e]:(t[e]=r,this)}function v(t,e){return e.split(" ").forEach(function(e){n(t,e)}),this}function p(t,e){return void 0===e?t.textContent:(t.textContent=null==e?"":""+e,this)}function h(t,e){if(void 0===e){if(t.multiple){var n=x.call(r.find(t,"option"),function(t){return t.selected});return s(n,"value")}return t.value}return t.value=e,this}function m(){return m}var b=Array.prototype.map,x=Array.prototype.filter,g=e.camelCase,y=e.deserializeValue,A=/([A-Z])/g,C={tabindex:"tabIndex",readonly:"readOnly","for":"htmlFor","class":"className",maxlength:"maxLength",cellspacing:"cellSpacing",cellpadding:"cellPadding",rowspan:"rowSpan",colspan:"colSpan",usemap:"useMap",frameborder:"frameBorder",contenteditable:"contentEditable"};return e.mixin(m,{attr:i,data:c,pluck:s,prop:d,removeAttr:v,removeData:f,text:p,val:h}),t.datax=m});
//# sourceMappingURL=sourcemaps/datax.js.map
