/**
 * skylark-utils - An Elegant HTML5 JavaScript Library.
 * @author Hudaokeji Co.,Ltd
 * @version v0.9.0
 * @link www.skylarkjs.org
 * @license MIT
 */
define(["./skylark","./langx","./noder","./datax","./geom","./eventer","./styler"],function(e,r,a,n,t,g,s){function i(e,r){return new c(e,r)}function d(e,r){return new u(e,r)}function o(){return o}var f=(g.on,g.off,n.attr,n.removeAttr,t.pagePosition,s.addClass,t.height,r.Evented.inherit({klassName:"DndManager",init:function(){},start:function(e,a){var n=t.pagePosition(e.elm);this.draggingOffsetX=parseInt(a.pageX-n.left),this.draggingOffsetY=parseInt(a.pageY-n.top);var s=g.create("started",{ghost:null,transfer:{}});e.trigger(s),this.dragging=e,this.draggingGhost=s.ghost,this.draggingGhost||(this.draggingGhost=e.elm),this.draggingTransfer=s.transfer,this.draggingTransfer&&r.each(this.draggingTransfer,function(e,r){a.dataTransfer.setData(e,r)}),a.dataTransfer.setDragImage(this.draggingGhost,this.draggingOffsetX,this.draggingOffsetY),a.dataTransfer.effectAllowed="copyMove",this.trigger(s)},end:function(){var e=g.create("ended",{});this.trigger(e),this.dragging=null,this.draggingTransfer=null,this.draggingGhost=null,this.draggingOffsetX=null,this.draggingOffsetY=null}})),l=new f,c=r.Evented.inherit({klassName:"Draggable",init:function(e,a){var t=this,i=a.draggingClass||"dragging",d=!1;t.elm=e,t._params=a,["started","ended","moving"].forEach(function(e){r.isFunction(a[e])&&t.on(e,a[e])}),g.on(e,{mousedown:function(e){d===!0&&n.prop(t.elm,"draggable",!0)},mouseup:function(e){n.prop(t.elm,"draggable",!1)},dragstart:function(e){l.start(t,e),s.addClass(t.elm,i)},dragend:function(e){g.stop(e),l.dragging&&(s.removeClass(t.elm,i),l.end())}}),a.handle?g.on(e,{mouseenter:function(e){d=!0},mouseleave:function(e){d=!1}},a.handle):d=!0}}),u=r.Evented.inherit({klassName:"Droppable",init:function(e,a){var n,t,i=this,d=(a.draggingClass||"dragging",!0);i.elm=e,i._params=a,["started","ended","entered","leaved","dropped","overing"].forEach(function(e){r.isFunction(a[e])&&i.on(e,a[e])}),g.on(e,{dragover:function(e){if(e.stopPropagation(),d){var r=g.create("overing",{transfer:l.draggingTransfer});i.trigger(r),e.preventDefault(),e.dataTransfer.dropEffect="copyMove"}},dragenter:function(e){var r=(i._params,i.elm),a=g.create("entered",{transfer:l.draggingTransfer});i.trigger(a),e.stopPropagation(),n&&d&&s.addClass(r,n)},dragleave:function(e){var r=(i._params,i.elm);if(!d)return!1;var a=g.create("leaved",{transfer:l.draggingTransfer});i.trigger(a),e.stopPropagation(),n&&d&&s.removeClass(r,n)},drop:function(e){var r=(i._params,i.elm);if(g.stop(e),l.dragging){n&&d&&s.addClass(r,n);var a=g.create("dropped",{transfer:l.draggingTransfer});i.trigger(a),l.end()}}}),l.on("started",function(r){var a=g.create("started",{transfer:l.draggingTransfer,acceptable:!1});i.trigger(a),d=a.acceptable,n=a.hoverClass,t=a.activeClass,t&&d&&s.addClass(e,t)}).on("ended",function(r){var a=g.create("ended",{transfer:l.draggingTransfer,acceptable:!1});i.trigger(a),n&&d&&s.removeClass(e,n),t&&d&&s.removeClass(e,t),d=!1,t=null,n=null})}});return r.mixin(o,{draggable:i,droppable:d,manager:l}),e.dnd=o});
//# sourceMappingURL=sourcemaps/dnd.js.map
