/**
 * skylark-utils - An Elegant HTML5 JavaScript Library.
 * @author Hudaokeji Co.,Ltd
 * @version v0.9.0
 * @link www.skylarkjs.org
 * @license MIT
 */
define(["./skylark","./langx","./browser","./styler","./eventer","./async"],function(n,i,t,e,s,o){function r(n,t,r,a,c,u){var f,p,d,m={},P=[],k="",F=this,O=!1,S=!1;if(i.isPlainObject(r)&&(a=r.easing,c=r.complete,u=r.delay,r=r.duration),i.isString(r)&&(r=y.speeds[r]),void 0===r&&(r=y.speeds.normal),r/=1e3,y.off&&(r=0),i.isFunction(a)?(c=a,eace="swing"):a=a||"swing",u?u/=1e3:u=0,i.isString(t))m[h]=t,m[g]=r+"s",m[v]=a,p=w;else{for(f in t)x.test(f)?k+=f+"("+t[f]+") ":("scrollTop"===f&&(S=!0),m[f]=t[f],P.push(i.dasherize(f)));p=I}return k&&(m[E]=k,P.push(E)),r>0&&i.isPlainObject(t)&&(m[z]=P.join(", "),m[C]=r+"s",m[b]=u+"s",m[T]=a),d=function(i){if(O=!0,i){if(i.target!==i.currentTarget)return;s.off(i.target,p,d)}else s.off(n,w,d);e.css(n,j),c&&c.call(this)},r>0&&(s.on(n,p,d),o.debounce(function(){O||d.call(F)},1e3*(r+u)+25)()),n.clientLeft,e.css(n,m),r<=0&&o.debounce(function(){O||d.call(F)},0)(),S&&l(n,t.scrollTop,r,c),this}function a(n,t,s){return e.show(n),t&&(!s&&i.isFunction(t)&&(s=t,t="normal"),e.css(n,"opacity",0),r(n,{opacity:1,scale:"1,1"},t,s)),this}function c(n,t,s){return t?(!s&&i.isFunction(t)&&(s=t,t="normal"),r(n,{opacity:0,scale:"0,0"},t,function(){e.hide(n),s&&s.call(n)})):e.hide(n),this}function l(n,i,t,e){var s=parseInt(n.scrollTop),r=0,a=5,c=1e3*t/a,l=parseInt(i),u=setInterval(function(){r++,r<=c&&(n.scrollTop=(l-s)/c*r+s),r>=c+1&&(clearInterval(u),e&&o.debounce(e,1e3)())},a)}function u(n,i,t){return e.isInvisible(n)?a(n,i,t):c(n,i,t),this}function f(n,i,t,e){return r(n,{opacity:t},i,e),this}function p(n,i,t){var s=e.css(n,"opacity");return s>0?e.css(n,"opacity",0):s=1,e.show(n),f(n,i,s,t),this}function d(n,i,t){return f(n,i,0,function(){e.hide(n),t&&t.call(n)}),this}function m(n,i,t){return e.isInvisible(n)?p(n,i,t):d(n,i,t),this}function y(){return y}var h,g,v,P,z,C,T,b,w=t.normalizeCssEvent("AnimationEnd"),I=t.normalizeCssEvent("TransitionEnd"),x=/^((translate|rotate|scale)(X|Y|Z|3d)?|matrix(3d)?|perspective|skew(X|Y)?)$/i,E=t.css3PropPrefix+"transform",j={};return j[h=t.normalizeCssProperty("animation-name")]=j[g=t.normalizeCssProperty("animation-duration")]=j[P=t.normalizeCssProperty("animation-delay")]=j[v=t.normalizeCssProperty("animation-timing-function")]="",j[z=t.normalizeCssProperty("transition-property")]=j[C=t.normalizeCssProperty("transition-duration")]=j[b=t.normalizeCssProperty("transition-delay")]=j[T=t.normalizeCssProperty("transition-timing-function")]="",i.mixin(y,{off:!1,speeds:{normal:400,fast:200,slow:600},animate:r,fadeIn:p,fadeOut:d,fadeTo:f,fadeToggle:m,hide:c,scrollToTop:l,show:a,toggle:u}),n.fx=y});
//# sourceMappingURL=sourcemaps/fx.js.map
