/**
 * skylark-utils - An Elegant HTML5 JavaScript Library.
 * @author Hudaokeji Co.,Ltd
 * @version v0.9.0
 * @link www.skylarkjs.org
 * @license MIT
 */
define(["./skylark","./langx"],function(e,t){function r(e,t){return"number"!=typeof t||v[h(e)]?t:t+"px"}function s(e){return e in g?g[e]:g[e]=new RegExp("(^|\\s)"+e+"(\\s|$)")}function n(e,t){var r=e.className||"",s=r&&void 0!==r.baseVal;return void 0===t?s?r.baseVal:r:void(s?r.baseVal=t:e.className=t)}function i(e){var t,r;return k[e]||(t=document.createElement(e),document.body.appendChild(t),r=getComputedStyle(t,"").getPropertyValue("display"),t.parentNode.removeChild(t),"none"==r&&(r="block"),k[e]=r),k[e]}function a(e){return C.css(e,"display",""),"none"==C.css(e,"display")&&C.css(e,"display",i(e.nodeName)),this}function o(e){return"none"==C.css(e,"display")||0==C.css(e,"opacity")}function l(e){return C.css(e,"display","none"),this}function c(e,r){if(!r)return this;var i,a=n(e);return i=t.isString(r)?r.split(/\s+/g):r,i.forEach(function(e){var t=s(e);a.match(t)||(a+=(a?" ":"")+e)}),n(e,a),this}function u(e,s,n){if(arguments.length<3){var i,i=getComputedStyle(e,"");if(t.isString(s))return e.style[m(s)]||i.getPropertyValue(s);if(t.isArrayLike(s)){var a={};return d.call(s,function(t){a[t]=e.style[m(t)]||i.getPropertyValue(t)}),a}}var o="";if("string"==typeof s)n||0===n?o=h(s)+":"+r(s,n):e.style.removeProperty(h(s));else for(key in s)void 0!==s[key]&&(s[key]||0===s[key]?o+=h(key)+":"+r(key,s[key])+";":e.style.removeProperty(h(key)));return e.style.cssText+=";"+o,this}function y(e,t){var r=s(t);return e.className&&e.className.match(r)}function f(e,r){var i,a=n(e);return i=t.isString(r)?r.split(/\s+/g):r,i.forEach(function(e){var t=s(e);a.match(t)&&(a=a.replace(t," "))}),n(e,a.trim()),this}function p(e,t,r){var s=this;return t.split(/\s+/g).forEach(function(t){void 0===r&&(r=!s.hasClass(e,t)),r?s.addClass(e,t):s.removeClass(e,t)}),s}var d=(Array.prototype.every,Array.prototype.forEach),m=t.camelCase,h=t.dasherize,v={"column-count":1,columns:1,"font-weight":1,"line-height":1,opacity:1,"z-index":1,zoom:1},g={},k={},C=function(){return C};return t.mixin(C,{autocssfix:!0,addClass:c,className:n,css:u,hasClass:y,hide:l,isInvisible:o,removeClass:f,show:a,toggleClass:p}),e.styler=C});
//# sourceMappingURL=sourcemaps/styler.js.map
