/**
 * skylark-utils - An Elegant HTML5 JavaScript Library.
 * @author Hudaokeji Co.,Ltd
 * @version v0.9.0
 * @link www.skylarkjs.org
 * @license MIT
 */
define(["./skylark","./langx","./datax","./dnd","./eventer","./filer","./finder","./fx","./geom","./mover","./noder","./styler"],function(e,t,n,o,r,i,a,l,s,d,c,f){function g(e,n){return function(){var o=this,r=o.domNode,i=e.apply(n,[r].concat(u.call(arguments)));if(i){if(i===n)return o;i instanceof HTMLElement?i=new m(i):t.isArrayLike(i)&&(i=p.call(i,function(e){return e instanceof HTMLElement?new m(i):e}))}return i}}var p=Array.prototype.map,u=Array.prototype.slice,m=t.klass({klassName:"VisualElement",init:function(e){t.isString(e)&&(e=document.getElementById(e)),this.domNode=e}}),h=new m(document.body),v=function(e){return e?new m(e):h};return t.mixin(v,{batch:function(e,t,n){return e.forEach(function(e){var o=e instanceof m?e:v(e);o[t].apply(o,n)}),this},root:new m(document.body),VisualElement:m,delegate:function(e,t){var n={};e.forEach(function(e){n[e]=g(t[e],t)}),m.partial(n)}}),v.delegate(["attr","data","prop","removeAttr","removeData","text","val"],n),v.delegate(["draggable","droppable"],o),v.delegate(["off","on","one","shortcuts","trigger"],r),v.delegate(["picker","dropzone"],i),v.delegate(["ancestor","ancestors","children","descendant","find","findAll","firstChild","lastChild","matches","nextSibling","nextSiblings","parent","previousSibling","previousSiblings","siblings"],a),v.find=function(e){return"body"===e?this.root:this.root.descendant(e)},v.delegate(["animate","fadeIn","fadeOut","fadeTo","fadeToggle","hide","scrollToTop","show","toggle"],l),v.delegate(["borderExtents","boundingPosition","boundingRect","clientHeight","clientSize","clientWidth","contentRect","height","marginExtents","offsetParent","paddingExtents","pagePosition","pageRect","relativePosition","relativeRect","scrollIntoView","scrollLeft","scrollTop","size","width"],s),v.delegate(["movable"],o),v.delegate(["after","append","before","clone","contains","contents","empty","html","isChildOf","ownerDoc","prepend","remove","replace","reverse","throb","traverse","wrapper","wrapperInner","unwrap"],c),v.delegate(["addClass","className","css","hasClass","hide","isInvisible","removeClass","show","toggleClass"],f),e.velm=v});
//# sourceMappingURL=sourcemaps/velm.js.map
